- hosts: all
  tasks:
  - name: Install all updates
    apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes
      autoclean: yes
  - name: Set timezone to Europe/Amsterdam
    timezone:
      name: Europe/Amsterdam      
  - name: Install postgres
    apt:
      name: postgresql
  - name: Install packages
    apt:
      name:
        - python3
        - python3-pip
        - wget
        - bzr
        - git
        - gdebi-core
  - name: Install wkhtmltopdf
    action: shell sudo wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb -P /tmp ; sudo dpkg -i /tmp/wkhtmltox_0.12.5-1.bionic_amd64.deb ; sudo rm -f /tmp/wkhtmltox_0.12.5-1.bionic_amd64.deb ; sudo ln -s /usr/local/bin/wkhtmltopdf /usr/bin ; sudo ln -s /usr/local/bin/wkhtmltoimage /usr/bin
  - name: install python packages
    pip:
      name:
        - xlrd
        - num2words
        - xlwt
        - phonenumbers
        - qrcode
      executable: pip3
  - name: Install Odoo
    action: shell sudo wget http://nightly.odoo.com/13.0/nightly/deb/odoo_13.0.latest_all.deb -P /tmp ; sudo dpkg -i /tmp/odoo_13.0.latest_all.deb ; sudo apt-get install -f -y ; sudo rm -f /tmp/odoo_13.0.latest_all.deb
  - name: Create custom addons dir
    action: shell sudo mkdir -p /opt/odoo/addons
  - name: Config Odoo
    copy:
      src: odoo.conf
      dest: /etc/odoo/
  - name: Restart Odoo
    service:
      name: odoo
      state: restarted
